target-version = "py39"
line-length = 99

[lint]
preview = true
select = ["ALL"]
ignore = [
  "D", "S101", "TD003", "FIX002", "PLR0912", "PLR0913", "RET505", "RET506", "TRY003",
  "PLR2004", "G004", "C901", "PLR0915", "S311", "SIM108", "PLW2901", "G003", "TCH003",
  "UP007", "ARG002", "ANN101", "ANN204", "ANN002", "ANN003", "ANN401", "ANN102", "CPY",
  "E116", "PLR1702", "PLR0914",
]
